# Generated by Django 2.2 on 2020-10-23 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bancos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Equities',
            fields=[
                ('equity', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('sector1', models.CharField(max_length=200)),
                ('sector2', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['equity'],
            },
        ),
        migrations.CreateModel(
            name='Nis_pos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechacompra', models.DateField(verbose_name='fecha compra')),
                ('Cantidad', models.IntegerField()),
                ('precio_compra', models.FloatField()),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Bancos')),
                ('equity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Equities')),
            ],
        ),
    ]
